chore(TDI-48973): Fix Sonar NoClassDefFoundError (#662)
* chore(TDI-48973): Fix Sonar NoClassDefFoundError

Disables Sonar cache due to "ClassNotFoundException: com.google.common.collect.LinkedListMultimap" issue (https://community.sonarsource.com/t/sonarscanner-for-maven-broken-with-sonarqube-9-5/67061/8). To be removed on next SonarQube upgrade (9.7.1+)

* chore(TDI-48973): Fix Sonar NoClassDefFoundError

Add Jira to reactivate Sonar Cache

* chore(TDI-48973): Fix Sonar NoClassDefFoundError

Update TODO line