feat(TCOMP-2023): Upgrade gradle to 6.9.1
- also bump gmavenplus-maven-plugin to 1.13.0

- this fixes java.lang.NoClassDefFoundError since jdk 14+:
`Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7`

- fix changes on gradlew.bat command line